### ISSUE TITLE
Assertion Error when saving DianaVampire2017Asherz.esp (Conversion to Form 44)

### ISSUE THREAD

**Issue by scjohnson1981** [Nukem9/SkyrimSETest#16]
I'm getting the following Assertion Error when attempting to save DianaVampire2017Asherz.esp in the SSE CK:

FAULTING_IP: 
CreationKit+121d4da
00000001`4121d4da 8b4014          mov     eax,dword ptr [rax+14h]

EXCEPTION_RECORD:  ffffffffffffffff -- (.exr 0xffffffffffffffff)
ExceptionAddress: 000000014121d4da (CreationKit+0x000000000121d4da)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: ffffffffffffffff
Attempt to read from address ffffffffffffffff

DEFAULT_BUCKET_ID:  INVALID_POINTER_READ

PROCESS_NAME:  CreationKit.exe

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at "0x%08lx" referenced memory at "0x%08lx". The memory could not be "%s".

EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - The instruction at "0x%08lx" referenced memory at "0x%08lx". The memory could not be "%s".

EXCEPTION_PARAMETER1:  0000000000000000

EXCEPTION_PARAMETER2:  ffffffffffffffff

READ_ADDRESS:  ffffffffffffffff 

FOLLOWUP_IP: 
CreationKit+121d4da
00000001`4121d4da 8b4014          mov     eax,dword ptr [rax+14h]

NTGLOBALFLAG:  0

FAULTING_THREAD:  0000000000003e70

PRIMARY_PROBLEM_CLASS:  INVALID_POINTER_READ

BUGCHECK_STR:  APPLICATION_FAULT_INVALID_POINTER_READ

LAST_CONTROL_TRANSFER:  from 000000014169120e to 000000014121d4da

STACK_TEXT:  
00000000`0012c488 00000001`4169120e : 3104b301`00000000 00000000`6dad4a20 00000000`00000008 00000001`27940b30 : CreationKit+0x121d4da
00000000`0012c490 3104b301`00000000 : 00000000`6dad4a20 00000000`00000008 00000001`27940b30 00103a90`00000000 : CreationKit+0x169120e
00000000`0012c498 00000000`6dad4a20 : 00000000`00000008 00000001`27940b30 00103a90`00000000 00000001`00000008 : 0x3104b301`00000000
00000000`0012c4a0 00000000`00000008 : 00000001`27940b30 00103a90`00000000 00000001`00000008 ffffffff`fffffffe : 0x6dad4a20
00000000`0012c4a8 00000001`27940b30 : 00103a90`00000000 00000001`00000008 ffffffff`fffffffe 00000000`00000000 : 0x8
00000000`0012c4b0 00103a90`00000000 : 00000001`00000008 ffffffff`fffffffe 00000000`00000000 00000000`0012c501 : 0x1`27940b30
00000000`0012c4b8 00000001`00000008 : ffffffff`fffffffe 00000000`00000000 00000000`0012c501 00000000`6dad4a20 : 0x103a90`00000000
00000000`0012c4c0 ffffffff`fffffffe : 00000000`00000000 00000000`0012c501 00000000`6dad4a20 00000000`6dad4a30 : 0x1`00000008
00000000`0012c4c8 00000000`00000000 : 00000000`0012c501 00000000`6dad4a20 00000000`6dad4a30 00000000`00000010 : 0xffffffff`fffffffe

STACK_COMMAND:  ~0s; .ecxr ; kb

SYMBOL_STACK_INDEX:  0

SYMBOL_NAME:  CreationKit+121d4da

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: CreationKit

IMAGE_NAME:  CreationKit.exe

DEBUG_FLR_IMAGE_TIMESTAMP:  59c0175d

FAILURE_BUCKET_ID:  INVALID_POINTER_READ_c0000005_CreationKit.exe!Unknown

BUCKET_ID:  X64_APPLICATION_FAULT_INVALID_POINTER_READ_CreationKit+121d4da

WATSON_STAGEONE_URL:  http://watson.microsoft.com/StageOne/CreationKit_exe/1_5_3_0/59c0175d/CreationKit_exe/1_5_3_0/59c0175d/c0000005/0121d4da.htm?Retriage=1

Followup: MachineOwner

Here's a link to the .dmp Windows created when the SSE CK crashed:

https://www.dropbox.com/s/iatnb2wbch01w99/CreationKit.exe_20190114_054529.dmp?dl=0

Please fix this.  Thank you.

**Comment by Nukem9** [comment]
As I understand it the mod author is responsible for breaking it - certain records are malformed (manual edits via xEdit)? The [fix](https://github.com/Nukem9/SkyrimSETest/commit/db5c871f18d36565656aa37d99497ee0113cf2c1) is enough to get it loading/saving in the CK. Hopefully the game is okay with it.
