### ISSUE TITLE
SSE CK Update

### ISSUE THREAD

**Issue by scjohnson1981** [Nukem9/SkyrimSETest#18]
Don't know if you're aware or not but the Skyrim SE CK was updated on 3/13/19 alongside Skyrim SE & now the various fixes provided by SSE Creation Kit Fixes will no longer work.  Please update SSE Creation Kit Fixes to the new CK version as time allows.  Thank you.

**Comment by somerandomuser1** [comment]
^ seconded

I just now discovered these "fixes" and i cant even use them.

is there a way to get the old CK?

**Comment by somerandomuser1** [comment]
update

i found it

https://mega.nz/#!mJ8i3IzL!GVxaRhXC7N85kHgMqCkirGPJBdy-mUGe-2WrLrNAuBc

not my upload. uploaded by a user from nexus. use at your own risk. (i checked it against virustotal and it seems ok to me)

**Comment by Nukem9** [comment]
The link above should be enough, nothing else besides the exe needs to be replaced. As I mentioned on the nexus, I don't plan on supporting the updated CK version.

**Comment by lmstearn** [comment]
Wanna hand with it? My RE skills are minimal, and won't be set up with SSE until at least a month from now. Cheers, Laurie.

**Comment by Nukem9** [comment]
There's not much to it besides comparing the exes.

For example https://github.com/Nukem9/SkyrimSETest/blob/master/skyrim64_test/src/patches/patches_ckit.cpp#L121:
`g_ModuleBase + 0x1770560` (1.5.30) would change to `g_ModuleBase + 0x176F340` (1.5.73)

There's also a few instances of AutoFunc/AutoPtr with the same idea: https://github.com/Nukem9/SkyrimSETest/blob/master/skyrim64_test/src/patches/CKIT/Editor.cpp#L774

Every offset under the /CKIT/ directory needs to be updated.
