### ISSUE TITLE
Could not get flowchart class object

### ISSUE THREAD

**Issue by TheFBplus** [Nukem9/SkyrimSETest#19]
Every time I try to open the dialogue views in a quest it show up:
![image](https://user-images.githubusercontent.com/33896027/62222159-7565cf80-b3e5-11e9-8746-39dad28e5631.png)
After clicking confirm:
![image](https://user-images.githubusercontent.com/33896027/62222207-8ca4bd00-b3e5-11e9-97fb-e7f4f57d2959.png)
Reinstall CK can not solve this problem,do you have any advice?Thank you.

**Comment by Nukem9** [comment]
The CK must be run as an administrator.

**Comment by TheFBplus** [comment]
Thanks a lot :smile:
