### ISSUE TITLE
Change keyboard shortcuts

### ISSUE THREAD

**Issue by cesm1980** [Nukem9/SkyrimSETest#22]
This is a suggestion for a feature, can this be implemented later? It would be incredibly useful to be able to change the keyboard shortcuts, even if it's just by a .ini file or by some other means, i hope it's possible...

**Comment by Nukem9** [comment]
If by shortcuts you mean the "Render Window Hotkeys" dialog under the Edit menu, then yes it's possible to change them. Any other keyboard shortcuts not listed there are hardcoded and a huge pain to patch.

**Comment by cesm1980** [comment]
well... it wasn't just those but yeah even if i could change these from render window it would be good, but wait is there anyway way to users corrently change them without having to ask you? there's two columns there, one is current hotkey and the other is default hotkey so is there a way to change them currently ?

**Comment by Nukem9** [comment]
There's no way to change them currently. I'd have to add them to `skyrim64_test.ini` as custom options.

**Comment by cesm1980** [comment]
Ok thanks

**Comment by Nukem9** [comment]
https://github.com/Nukem9/SkyrimSETest/commit/d1eb194cbac6e447c6f935c29c2a22ded978e30a / Version 3.0
