### ISSUE TITLE
Specularity / character lighting bug

### ISSUE THREAD

**Issue by Nukem9** [Nukem9/SkyrimSETest#9]
watch?v=IUbUIVQZfS0

**Comment by pritster5** [comment]
I believe this bug can't be fixed without editing some engine code (Bethesda will have to take notice). Boris has said that this isn't fixable by patching shaders.

**Comment by Nukem9** [comment]
I've already rewritten the engine code part, there's nothing immediately obvious about it being broken: https://github.com/Nukem9/SkyrimSETest/blob/master/skyrim64_test/src/patches/TES/BSShader/Shaders/BSLightingShader.cpp#L683

The shader code has to be screwed up somewhere - the large # of shaders to patch is the real problem.

**Comment by pritster5** [comment]
IIRC didn't you make a tool to patch the shaders faster? Or was it a parser?

**Comment by Nukem9** [comment]
Yeah, I made a parser to extract variable/sampler/texture names but that doesn't make the code readable

**Comment by ArtaiosGreybark** [comment]
The video seems to be down.

**Comment by scjohnson1981** [comment]
This has been fixed by aers & Boris (ENB Binaries 0.370).  Good luck getting Bethesda to fix their broken shaders.
